---
- name: Enable UFW
  service: name=ufw state=started

- name: Allow HTTP traffic
  ufw: rule=allow port=80 proto=tcp

- name: Install NGINX
  apt: name=nginx update_cache=yes

- name: start NGINX
  service: name=nginx state=started

- name: Copy configuration file
  copy: src=main.yml dest=/etc/nginx/sites-available/default

- name: Restart NGINX
  service: name=nginx state=restarted
